baseURL: 'https://blog.c0nrad.io/'
languageCode: en-us
title: c0nrad's blog
theme: anubis
paginate: 10
googleAnalytics: "UA-165926825-2"


Menus:
  main:
    - name: About
      url: "https://c0nrad.io"
    - Name: Github
      URL: 'https://github.com/c0nrad/'
    - Name: Twitter
      URL: 'https://twitter.com/xc0nradx'

params:
  description: "Learning about physics"
  author: "Stuart Larsen"
  images:
    - static/walljump.gif
  customCSS:
    - css/my.css

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  