baseURL: "https://blog.c0nrad.io/"
languageCode: en-us
title: c0nrad's c0rner
theme: Hugo-Octopress

pagination:
  pagerSize: 10


menu:
  main:
    - name: Home
      url: "/"
      weight: -11
    - name: Website
      url: "https://c0nrad.io"
      weight: -10
    - Name: Github
      URL: "https://github.com/c0nrad/"
      weight: -9
    - Name: Twitter
      URL: "https://twitter.com/c0nrad_jr"
      weight: -8
    - Name: Other Blog
      URL: "https://c0nradsc0rner.com"
      weight: -7
  sidebar:
    - Name: CTFs
      URL: /categories/ctfs
      weight: 10
    - Name: physics
      URL: /categories/physics
      weight: 10
    - Name: electronics
      URL: /categories/electronics
      weight: 20
    - Name: quantum computing
      URL: /categories/quantum-computation
      weight: 10
    - Name: personal
      URL: /categories/personal
      weight: 30

params:
  subtitle: "Learning and learning"
  description: "Learning about physics"
  author: "Stuart Larsen"
  images:
    - static/walljump.gif
  customCSS:
    - css/my.css
  compactIndex: true

  sidebarRecentLimit: 0
  sidebarHeader: Who am I?
  sidebarText: |-
    <img src="/me.png" style="width: 100%"> 
    CTFs (<a href="https://www.youtube.com/@SloppyJoePirates/videos">Sloppy Joe Pirates</a>). Founder (<a href="https://csper.io">csper.io</a>). Enjoyer of security/software/physics.

  # Enable links in the side bar. They are under menu.sidebar.
  sidebarMenuEnabled: true
  # Name of the links section.
  sidebarMenuHeader: Collections

  generateTaxonomyList: true

  rss: true

  defaultKeywords:
    - Stuart Larsen
    - c0nrad
    - physics
    - ctfs

  tableOfContents: true

  twitterCardEnabled: true
  twitterCardDomain: blog.c0nrad.io
  twitterCardAuthor: CryptoGangsta

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
